version: "3"
services:
  chrome:
    image: selenium/standalone-chrome:4.22.0
    hostname: chrome
    privileged: true
    shm_size: 2gb
    ports:
      - "4441:4444"
      - "7901:7900"
    environment:
      - SE_VNC_NO_PASSWORD=1
      - SE_NOE_MAX_SESSIONS=1
  firefox:
    image: selenium/standalone-firefox
    hostname: firefox
    privileged: true
    shm_size: 2gb
    ports:
      - "4442:4444"
      - "7902:7990"
    environment:
      - SE_VNC_NO_PASSWORD=1
      - SE_NOE_MAX_SESSIONS=1